# Generated by Django 4.0.2 on 2022-10-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('domain', models.URLField(blank=True)),
                ('id_provider', models.CharField(max_length=10)),
            ],
        ),
    ]
